### ISSUE TITLE
[ShareView] 상태 설명 작성 뷰의 텍스트 작성 공간과 저장 버튼 추가

### ISSUE THREAD

**Issue by seunghoria** [DeveloperAcademy-POSTECH/MC2-Team11-EZ#10]
## 💡 Issue
상태 미니뷰 하단에 textEditor를 활용하여 상태를 상세 설명할 수 있는 공간을 추가한다.
상세 설명을 저장하는 버튼 추가한다.

## 📝  Todo
- [x] textEditor 과 textField의 차이
- [x] textEditor에 placeholder 추가
- [x] GeometryReader 파악
- [x] EmojiCardDetail 뷰 위치 설정

**Comment by seunghoria** [comment]
완료되었습니다!
